"""add length column to movies

Revision ID: 37085de2ab19
Revises: 889142213ee8
Create Date: 2026-06-30 02:17:37.911217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37085de2ab19'
down_revision: Union[str, Sequence[str], None] = '889142213ee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'watchlist', type_='foreignkey')
    op.drop_constraint(None, 'watchlist', type_='foreignkey')
    op.create_foreign_key(None, 'watchlist', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'watchlist', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watchlist', type_='foreignkey')
    op.drop_constraint(None, 'watchlist', type_='foreignkey')
    op.create_foreign_key(None, 'watchlist', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'watchlist', 'movies', ['movie_id'], ['id'])
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'reviews', 'movies', ['movie_id'], ['id'])
    # ### end Alembic commands ###
