"""lenght --> length

Revision ID: 889142213ee8
Revises: 6ec508e618bc
Create Date: 2026-06-30 02:13:05.554477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '889142213ee8'
down_revision: Union[str, Sequence[str], None] = '6ec508e618bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('length', sa.Integer(), nullable=False))
    op.drop_column('movies', 'lenght')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'watchlist', type_='foreignkey')
    op.drop_constraint(None, 'watchlist', type_='foreignkey')
    op.create_foreign_key(None, 'watchlist', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'watchlist', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watchlist', type_='foreignkey')
    op.drop_constraint(None, 'watchlist', type_='foreignkey')
    op.create_foreign_key(None, 'watchlist', 'movies', ['movie_id'], ['id'])
    op.create_foreign_key(None, 'watchlist', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'movies', ['movie_id'], ['id'])
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['id'])
    op.add_column('movies', sa.Column('lenght', sa.INTEGER(), nullable=False))
    op.drop_column('movies', 'length')
    # ### end Alembic commands ###
